spring:
  datasource:
    url: jdbc:mysql://localhost:3308/final?createDatabaseIfNotExist=true
    username: root
    password: root
    schema: classpath:schema.sql
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQL8Dialect